inherit_from: .rubocop_todo.yml

plugins:
  - rubocop-rake
  - rubocop-rspec

AllCops:
  EnabledByDefault: true
  DefaultFormatter: fuubar
  TargetRubyVersion: 3.4

Layout/LineLength: { Max: 80 }
Layout/RedundantLineBreak: { InspectBlocks: true }
Naming/VariableNumber: { EnforcedStyle: snake_case }
RSpec/MessageExpectation:
  EnforcedStyle: expect
  Exclude: [spec/support/matchers/invoke_matcher.rb]
Style/ClassAndModuleChildren: { EnforcedStyle: compact }
Style/ClassMethodsDefinitions: { EnforcedStyle: self_class }

Style/MethodCallWithArgsParentheses:
  AllowedMethods:
    - and
    - describe
    - not_to
    - puts
    - raise
    - to

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Style/SymbolArray: { EnforcedStyle: brackets }
Style/TrailingCommaInArguments: { EnforcedStyleForMultiline: consistent_comma }
Style/TrailingCommaInArrayLiteral: { EnforcedStyleForMultiline: consistent_comma }
Style/TrailingCommaInHashLiteral: { EnforcedStyleForMultiline: consistent_comma }
Style/WordArray: { EnforcedStyle: brackets }

Bundler/GemComment: { Enabled: false }
Bundler/GemVersion: { Enabled: false }
Layout/SingleLineBlockChain: { Enabled: false }
Lint/ConstantResolution: { Enabled: false }
Style/ConstantVisibility: { Enabled: false }
Style/Copyright: { Enabled: false }
Style/MissingElse: { Enabled: false }
