name: Ruby

on:
  push:
    branches:
      - main

  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        ruby:
          - 3.4.1

    steps:
    - uses: actions/checkout@v2
    - name: Install ImageMagick
      uses: awalsh128/cache-apt-pkgs-action@latest
      with:
        packages: libmagickwand-dev
        version: 1.0
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - name: Run the default task
      run: bundle exec rake
